KeyDownP1 : s
KeyLeftP1 : q
KeyRightP1 : d
KeyUpP1 : z
KeyDownP2 : l
KeyLeftP2 : k
KeyRightP2 : m
KeyUpP2 : o
TokenP1 : Y
TokenP2 : X
ColorP1 : Green
ColorP2 : Red
BonusToken : O
Lang : fr
NbColumn : 20
NbRow : 10
BorderColor : BlackBG
BonusColor : Yellow
