KeyDownP1 : s
KeyLeftP1 : q
KeyRightP1 : d
KeyUpP1 : z
KeyDownP2 : l
KeyLeftP2 : k
KeyRightP2 : m
KeyUpP2 : o
KeyBonus1 : v
KeyBonus2 : b
TokenP1 : Y
TokenP2 : X
ColorP1 : Green
ColorP2 : Red
CoinsToken : o
BonusToken : B
Lang : es
NbColumn : 25
CoinsLimit : 10
NbRow : 15
BorderColor : BlackBG
BonusColor : MAgenta
CoinsColor : Yellow
